package com.test.dao;

import com.test.pojo.StuInfo;
import com.test.pojo.StuInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    int countByExample(StuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    int deleteByExample(StuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    int deleteByPrimaryKey(String stuno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    int insert(StuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    int insertSelective(StuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    List<StuInfo> selectByExample(StuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    StuInfo selectByPrimaryKey(String stuno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") StuInfo record, @Param("example") StuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    int updateByExample(@Param("record") StuInfo record, @Param("example") StuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    int updateByPrimaryKeySelective(StuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    int updateByPrimaryKey(StuInfo record);
}