package com.test.pojo;

import java.util.Date;

public class StuInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuNo
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    private String stuno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuPwd
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    private String stupwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuName
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    private String stuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gradeId
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    private Integer gradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.tel
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.address
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.bornDate
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    private Date borndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.email
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuNo
     *
     * @return the value of student.stuNo
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public String getStuno() {
        return stuno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuNo
     *
     * @param stuno the value for student.stuNo
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public void setStuno(String stuno) {
        this.stuno = stuno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuPwd
     *
     * @return the value of student.stuPwd
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public String getStupwd() {
        return stupwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuPwd
     *
     * @param stupwd the value for student.stuPwd
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public void setStupwd(String stupwd) {
        this.stupwd = stupwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuName
     *
     * @return the value of student.stuName
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuName
     *
     * @param stuname the value for student.stuName
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public void setStuname(String stuname) {
        this.stuname = stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gradeId
     *
     * @return the value of student.gradeId
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public Integer getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gradeId
     *
     * @param gradeid the value for student.gradeId
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.tel
     *
     * @return the value of student.tel
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.tel
     *
     * @param tel the value for student.tel
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.bornDate
     *
     * @return the value of student.bornDate
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public Date getBorndate() {
        return borndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.bornDate
     *
     * @param borndate the value for student.bornDate
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public void setBorndate(Date borndate) {
        this.borndate = borndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.email
     *
     * @return the value of student.email
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.email
     *
     * @param email the value for student.email
     *
     * @mbggenerated Mon Mar 12 15:56:06 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }
}